in
this
example
we
will
see
IOException
another
checked
exception